version: '3'

services:
  test:
    image: "node:12-alpine"
    build: .
    depends_on:
      - 'postgres'
    links:
      - postgres
    networks:
      - app-network
    volumes:
      - ${MY_WORKSPACE}:/ws
    working_dir: /ws${WORKSPACE_PATH:-/}
    user: ${MY_USER:-root}
    command: >
      sh -c "
        npm install &&
        npm run lint &&
        npm run build &&
        npm run test
      "

  postgres:
    image: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
